<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RepositoryUrl>https://github.com/WildernessLabs/Meadow.Foundation</RepositoryUrl>
    <PackageIcon>icon.png</PackageIcon>
    <PackageProjectUrl>http://developer.wildernesslabs.co/Meadow/Meadow.Foundation/</PackageProjectUrl>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <Company>Wilderness Labs, Inc</Company>
    <Authors>Wilderness Labs, Inc</Authors>
    <LangVersion>12.0</LangVersion>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\..\..\..\icon.png" Pack="true" PackagePath="" />
    <ProjectReference Include="..\..\Driver\ICs.IOExpanders.Ftxxxx.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="configs\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>