//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meadow.Foundation.Graphics {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmbeddedYaffFonts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmbeddedYaffFonts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Graphics.MicroGraphics.Fonts.EmbeddedYaffFonts", typeof(EmbeddedYaffFonts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name: Atari Classic 8x8
        ///spacing: character-cell
        ///cell-size: 8 8
        ///encoding: atascii
        ///converter: monobit v0.32
        ///source-name: REVAPAL.ROM
        ///source-format: binary
        ///
        ///
        ///# [ ] SPACE
        ///u+0020:
        ///0x00:
        ///    ........
        ///    ........
        ///    ........
        ///    ........
        ///    ........
        ///    ........
        ///    ........
        ///    ........
        ///
        ///
        ///# [!] EXCLAMATION MARK
        ///u+0021:
        ///0x01:
        ///    ........
        ///    ...@@...
        ///    ...@@...
        ///    ...@@...
        ///    ...@@...
        ///    ........
        ///    ...@@...
        ///    ........
        ///
        ///
        ///# [&quot;] QUOTATION MARK
        ///u+0022:
        ///0x02:
        ///    ..... [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Atari_Classic_yaff {
            get {
                return ResourceManager.GetString("Atari_Classic.yaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name: Chicago Regular 12
        ///spacing: proportional
        ///bounding-box: 13 15
        ///family: Chicago
        ///point-size: 12
        ///ascent: 12
        ///descent: 3
        ///line-height: 16
        ///encoding: mac-roman
        ///default-char: missing
        ///converter: monobit v0.32
        ///source-name: system608.suit
        ///source-format: MacOS FONT (AppleDouble container)
        ///history: load --format=mac-rsrc
        ///shift-up: -3
        ///
        ///0x00:
        ///    -
        ///
        ///0x09:
        ///    -
        ///
        ///    left-bearing: 8
        ///
        ///
        ///0x0d:
        ///    -
        ///
        ///u+2318:
        ///0x11:
        ///    .........
        ///    .........
        ///    .........
        ///    .@@...@@.
        ///    @..@.@..@
        ///    @ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Chicago_12_yaff {
            get {
                return ResourceManager.GetString("Chicago_12.yaff", resourceCulture);
            }
        }
    }
}
