<Project Sdk="Meadow.Sdk/1.1.0">
  <PropertyGroup>
    <Version>1.11.0</Version>
    <PackageReadmeFile>Readme.md</PackageReadmeFile>
    <Nullable>enable</Nullable>
    <LangVersion>10.0</LangVersion>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageIcon>icon.png</PackageIcon>
    <Authors>Wilderness Labs, Inc</Authors>
    <TargetFramework>netstandard2.1</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>CMBusMaster</AssemblyName>
    <Company>Wilderness Labs, Inc</Company>
    <PackageProjectUrl>http://developer.wildernesslabs.co/Meadow/Meadow.Foundation/</PackageProjectUrl>
    <PackageId>Meadow.Foundation.mikroBUS.Sensors.MBus.CMBusMaster</PackageId>
    <RepositoryUrl>https://github.com/WildernessLabs/Meadow.Foundation</RepositoryUrl>
    <PackageTags>Meadow,Meadow.Foundation,MikroBus,Mikroe,MikroElectronika,M-Bus,Meter-Bus</PackageTags>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Description>MikroElectronika Serial M-Bus MikroBus click board</Description>
  </PropertyGroup>
  <ItemGroup>
    <None Include=".\Readme.md" Pack="true" PackagePath="" />
    <None Include="..\..\..\..\icon.png" Pack="true" PackagePath="" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\..\Meadow.Foundation.MBus\Source\Driver\Meadow.MBus.csproj" />
  </ItemGroup>
</Project>
