<Project Sdk="Meadow.Sdk/1.1.0">
  <PropertyGroup>
    <PackageReadmeFile>Readme.md</PackageReadmeFile>
    <Nullable>enable</Nullable>
    <LangVersion>12.0</LangVersion>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageIcon>icon.png</PackageIcon>
    <Authors>Wilderness Labs, Inc</Authors>
    <TargetFramework>netstandard2.1</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>Sx1303</AssemblyName>
    <Company>Wilderness Labs, Inc</Company>
    <PackageProjectUrl>http://developer.wildernesslabs.co/Meadow/Meadow.Foundation/</PackageProjectUrl>
    <PackageId>Meadow.Foundation.ICs.LoRa.Sx1303</PackageId>
    <RepositoryUrl>https://github.com/WildernessLabs/Meadow.Foundation</RepositoryUrl>
    <PackageTags>Meadow,Meadow.Foundation,LoRa,LoRaWAN,SX1303,WaveShare,Gateway,Concentrator</PackageTags>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Description>Semtech SX1303 LoRaWAN multi-channel concentrator driver, as used on the WaveShare SX1303 915M LoRaWAN Gateway (B)</Description>
  </PropertyGroup>
  <ItemGroup>
    <None Include=".\Readme.md" Pack="true" PackagePath="" />
    <None Include="..\..\..\icon.png" Pack="true" PackagePath="" />
    <ProjectReference Include="..\..\..\Meadow.Foundation.Core\Meadow.Foundation.Core.csproj" />
  </ItemGroup>
</Project>
