<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>1.0.0</Version>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Authors>Wilderness Labs, Inc</Authors>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>Uds</AssemblyName>
    <Company>Wilderness Labs, Inc</Company>
    <PackageProjectUrl>http://developer.wildernesslabs.co/Meadow/Meadow.Foundation/</PackageProjectUrl>
    <PackageId>Meadow.Foundation.Telematics.Uds</PackageId>
    <PackageIcon>icon.png</PackageIcon>
    <RepositoryUrl>https://github.com/WildernessLabs/Meadow.Foundation</RepositoryUrl>
    <PackageTags>Meadow,Meadow.Foundation,UDS,ISO14229,Diagnostics</PackageTags>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Description>Lightweight Framework for UDS (ISO 14229) diagnostic client and server applications</Description>
    <Nullable>enable</Nullable>
    <LangVersion>12.0</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\..\..\icon.png" Pack="true" PackagePath="" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Meadow.Contracts" />
    <ProjectReference Include="..\..\Telematics.J1979\Driver\Telematics.J1979.csproj" />
  </ItemGroup>
</Project>
